<?php

return [

    'url' => [
        'blog' => '/blog/',
        'hoodie' => 'https://shop.spreadshirt.de/agile-punks/agile+punks+20-A5e2aea0ae447424d5b535303?productType=1047&sellable=xrXml797dlF13z9vNgjq-1047-22&appearance=2',
        'medium' => 'https://medium.com/agile-punks',
    ],
    'podcast' => [
        'channels' => [
            'spotify' => "Spotify",
            'apple' => "Apple Music",
            'podcast' => "podcast.de",
            'amazon' => "Amazon",
            'deezer' => "Deezer",
            'rss' => "RSS",
            'google' => "Google",
        ],
        'colors' => [
            'spotify' => "bg-punk-dark text-punk-green dark:bg-darkpunk-dark dark:text-darkpunk-green ",
            'apple' => "bg-punk-red text-punk-light dark:bg-darkpunk-red dark:text-darkpunk-light ",
            'podcast' => "bg-punk-brown text-punk-light dark:bg-darkpunk-brown dark:text-darkpunk-light ",
            'amazon' => "bg-punk-blue text-punk-light dark:bg-darkpunk-dark dark:text-darkpunk-light ",
            'deezer' => "bg-punk-dark text-punk-light dark:bg-darkpunk-blue dark:text-darkpunk-light ",
            'google' => "bg-punk-pink text-punk-dark dark:bg-darkpunk-light dark:text-darkpunk-brown ",
            'rss' => "bg-punk-light text-punk-brown dark:bg-darkpunk-pink dark:text-darkpunk-dark ",
        ],
    ],
    'cache' => [
        'blog_ttl' => 604800,
    ],
    'people' => [
        'domi' => [
            'name' => 'Dominic Burucker',
            'role' => 'punk',
            'display_name' => 'Dominic',
            'mail' => 'dominic@agile-punks.com',
            'image' => 'img/blog-domi.webp',
            'short_bio' => 'agent of change & servant leader',
            'since' => '2018',
            'linkedin' => 'https://www.linkedin.com/in/dominic-burucker-559b95181/',
        ],
        'ralph' => [
            'name' => 'Ralph Cibis',
            'role' => 'punk',
            'display_name' => 'Ralph',
            'mail' => 'ralph@agile-punks.com',
            'image' => 'img/blog-ralph.webp',
            'short_bio' => 'leadership & purpose',
            'since' => '2016',
            'linkedin' => 'https://www.linkedin.com/in/ralphcibis/',
        ],
        'max' => [
            'name' => 'Max Feldmann',
            'role' => 'punk',
            'display_name' => 'Max',
            'mail' => 'max@agile-punks.com',
            'image' => 'img/blog-max.webp',
            'short_bio' => 'products, backlogs & branding',
            'since' => '2017',
            'linkedin' => 'https://www.linkedin.com/in/max-feldmann/',
        ],
        'chereen' => [
            'name' => 'Chereen Heinrich',
            'role' => 'punk',
            'display_name' => 'Chereen',
            'mail' => 'chereen@agile-punks.com',
            'image' => 'img/blog-chereen.webp',
            'short_bio' => 'open mind & open heart',
            'since' => '2017',
            'linkedin' => 'https://www.linkedin.com/in/chereen-heinrich-cibis-52a92674/',
        ],
        'domiralph' => [
            'name' => 'Dominic Burucker & Ralph Cibis',
            'role' => 'author',
            'display_name' => 'Dominic & Ralph',
            'mail' => 'info@agile-punks.com',
            'image' => 'img/blog-domiralph.webp',
            'short_bio' => 'co-founders of agile punks',
            'since' => '2017',
            'magic_card_title' => 'not agile enough',
            'linkedin' => 'https://www.linkedin.com/company/agile-punks',
            'skills' => [],
        ],
    ],
];
